version: '3.8'

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: